<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Self-billed Refund Note_ant-input css-4fk4bg_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>69cef270-77c7-4c1e-ae7d-f92ffddf2087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SINV-F']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-4fk4bg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search by e-invoice No.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33ab7065-aaea-4802-b255-c10b278539d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by e-invoice No.</value>
      <webElementGuid>46e08a95-7dbd-4049-beeb-b428db830c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>443</value>
      <webElementGuid>dae507dc-73cb-4348-9342-442084582720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-4fk4bg</value>
      <webElementGuid>70396a6d-b3c0-4fc4-a469-1fa4d9ed60b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65a7da0e-10b2-4ef3-8109-7e260a6c1de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SINV-F</value>
      <webElementGuid>f7286810-3898-429b-9035-3a8e278e045e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-uaxenf ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-4fk4bg&quot;]/div[@class=&quot;ant-pro-layout-container css-uaxenf&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-uaxenf ant-pro-layout-has-header ant-pro-layout-content-has-page-container css-4fk4bg&quot;]/div[@class=&quot;ant-pro-page-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content-children css-uaxenf&quot;]/div[@class=&quot;css-uaxenf ant-pro-page-container-children-container&quot;]/div[@class=&quot;ant-card ant-card-bordered ant-card-small css-4fk4bg&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-pro-table invoice-list css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar css-uaxenf sqTableToolbar&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-right css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-search css-uaxenf&quot;]/span[@class=&quot;ant-input-group-wrapper ant-input-group-wrapper-outlined css-4fk4bg ant-input-search&quot;]/span[@class=&quot;ant-input-wrapper ant-input-group css-4fk4bg&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused css-4fk4bg ant-input-outlined&quot;]/input[@class=&quot;ant-input css-4fk4bg&quot;]</value>
      <webElementGuid>0598fa5a-c65f-48e0-b6fb-36fb887d146e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SINV-F']</value>
      <webElementGuid>1a9400cb-3660-40c9-8914-37292dd6f186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/main/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/span/span/span/input</value>
      <webElementGuid>f62289e8-f7fb-4ba0-a980-542aeb4aa930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>de5fe7d4-2bde-4518-970d-0135440f74f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search by e-invoice No.' and @type = 'text']</value>
      <webElementGuid>3fa72044-477d-4587-891e-50bd3a0dd0e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
