<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Self-billed Refund Note_ant-input css-4fk4bg_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>2c697fe3-dc81-43dc-b2be-538c8fcf7965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SINV-FC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-4fk4bg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search by e-invoice No.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f98f37a5-537f-4628-8b3e-a98ea7a2cd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by e-invoice No.</value>
      <webElementGuid>a5026aea-0aac-4464-9783-ffd6b4e8dbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>443</value>
      <webElementGuid>3a9034cc-8260-4e81-ae20-9a773e05a936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-4fk4bg</value>
      <webElementGuid>2fee304f-bf05-4263-bfa2-0a2d7b6ea9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5682e61f-9ea2-47e4-b102-67905a2a366c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SINV-FC</value>
      <webElementGuid>ad0532a4-bd6c-49f5-84e8-4d2f6ef5809c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-uaxenf ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-4fk4bg&quot;]/div[@class=&quot;ant-pro-layout-container css-uaxenf&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-uaxenf ant-pro-layout-has-header ant-pro-layout-content-has-page-container css-4fk4bg&quot;]/div[@class=&quot;ant-pro-page-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content-children css-uaxenf&quot;]/div[@class=&quot;css-uaxenf ant-pro-page-container-children-container&quot;]/div[@class=&quot;ant-card ant-card-bordered ant-card-small css-4fk4bg&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-pro-table invoice-list css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar css-uaxenf sqTableToolbar&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-right css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-search css-uaxenf&quot;]/span[@class=&quot;ant-input-group-wrapper ant-input-group-wrapper-outlined css-4fk4bg ant-input-search&quot;]/span[@class=&quot;ant-input-wrapper ant-input-group css-4fk4bg&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused css-4fk4bg ant-input-outlined&quot;]/input[@class=&quot;ant-input css-4fk4bg&quot;]</value>
      <webElementGuid>8e026e6e-adea-4544-a211-00cd1ab738e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SINV-FC']</value>
      <webElementGuid>02508432-811a-402e-9642-fc067576ef09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/main/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/span/span/span/input</value>
      <webElementGuid>b39be353-1096-4611-bac4-dc7e0544372c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>2fe711be-1f1e-4e0b-8908-11dc5a6a4145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search by e-invoice No.' and @type = 'text']</value>
      <webElementGuid>1df5921a-f14a-470b-ba55-52864b438f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
