<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Self-billed Refund Note_ant-input css-4fk4bg_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>9896bb04-a404-435c-a42c-dd1bbb5b0f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='SINV-FCG@']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-4fk4bg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search by e-invoice No.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60ac18bf-3850-4195-a14b-6acdd824e13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by e-invoice No.</value>
      <webElementGuid>93f63591-a195-4333-8e0c-3a5ffed7e162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>443</value>
      <webElementGuid>ad7fb1a1-078c-4997-b5d0-996100d00d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-4fk4bg</value>
      <webElementGuid>004fff38-a233-443f-bbc0-d0446da3593a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>587e5a10-a44a-4eb9-8bac-7dc35be674ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SINV-FCG@</value>
      <webElementGuid>1659e095-fa0d-402d-8b69-21e4b3e4f113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-uaxenf ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-4fk4bg&quot;]/div[@class=&quot;ant-pro-layout-container css-uaxenf&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-uaxenf ant-pro-layout-has-header ant-pro-layout-content-has-page-container css-4fk4bg&quot;]/div[@class=&quot;ant-pro-page-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content-children css-uaxenf&quot;]/div[@class=&quot;css-uaxenf ant-pro-page-container-children-container&quot;]/div[@class=&quot;ant-card ant-card-bordered ant-card-small css-4fk4bg&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-pro-table invoice-list css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar css-uaxenf sqTableToolbar&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-right css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-search css-uaxenf&quot;]/span[@class=&quot;ant-input-group-wrapper ant-input-group-wrapper-outlined css-4fk4bg ant-input-search&quot;]/span[@class=&quot;ant-input-wrapper ant-input-group css-4fk4bg&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused css-4fk4bg ant-input-outlined&quot;]/input[@class=&quot;ant-input css-4fk4bg&quot;]</value>
      <webElementGuid>b3c571a1-9b9b-4e26-9016-9a28636422ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SINV-FCG@']</value>
      <webElementGuid>db66c164-0bc8-4860-8fd4-d94fce8f27eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/main/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/span/span/span/input</value>
      <webElementGuid>0026f6eb-1ce7-477e-b37a-61454e499437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>45f80f87-0285-4e0d-a627-070355e902c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search by e-invoice No.' and @type = 'text']</value>
      <webElementGuid>7250966c-0525-4c06-8532-32fda37ca07c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
