<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice date_dateRange</name>
   <tag></tag>
   <elementGuidId>9d4565d0-4b0c-41a9-ad74-46ae33b238cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateRange']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dateRange</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Invoice date&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8983d79-b9d2-489f-9e27-e24b82888d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d68861df-1b02-4dd4-a9c5-356ca147b62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d27f21a-57d8-48ee-b133-16f6c752eede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>69b1857c-bbaa-430f-b99e-18050ea9f658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateRange</value>
      <webElementGuid>f43ea7bb-7e75-4ee1-afe5-e2c5daa0555d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start Date</value>
      <webElementGuid>2953f38f-1029-422d-83b5-8c79008a5c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>date-range</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>c0e86a35-44eb-4485-b082-5bffe8378858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-uaxenf ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-4fk4bg&quot;]/div[@class=&quot;ant-pro-layout-container css-uaxenf&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-uaxenf ant-pro-layout-has-header ant-pro-layout-content-has-page-container css-4fk4bg&quot;]/div[@class=&quot;ant-pro-page-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content-children css-uaxenf&quot;]/div[@class=&quot;css-uaxenf ant-pro-page-container-children-container&quot;]/div[@class=&quot;ant-card ant-card-bordered ant-card-small css-4fk4bg&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-pro-table invoice-list css-uaxenf&quot;]/div[@class=&quot;css-uaxenf ant-pro-card ant-pro-table-search ant-pro-table-search-query-filter sqInvoiceListFilter&quot;]/form[@class=&quot;ant-form ant-form-vertical css-4fk4bg ant-pro-query-filter css-uaxenf sqInvoiceListFilter ant-pro-form css-uaxenf&quot;]/div[@class=&quot;ant-row ant-row-start ant-pro-query-filter-row css-uaxenf css-4fk4bg&quot;]/div[@class=&quot;ant-col ant-col-12 ant-pro-query-filter-row-split css-uaxenf css-4fk4bg&quot;]/div[@class=&quot;ant-form-item css-4fk4bg&quot;]/div[@class=&quot;ant-row ant-form-item-row css-4fk4bg&quot;]/div[@class=&quot;ant-col ant-form-item-control css-4fk4bg&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-picker ant-picker-range ant-picker-focused ant-picker-outlined css-4fk4bg&quot;]/div[@class=&quot;ant-picker-input ant-picker-input-active&quot;]/input[@id=&quot;dateRange&quot;]</value>
      <webElementGuid>166eeb4b-c8e9-4be0-829f-8e43d57e7348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateRange']</value>
      <webElementGuid>30ca0a24-2492-4c4c-a2cd-5fa78373e91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/main/div[2]/div[2]/div/div/div/div/div/div/form/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>ba4d2f53-ed57-4713-90f3-b4e0f2cce91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b51e5701-0857-454b-bafa-7a5bea6a6de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateRange' and @placeholder = 'Start Date']</value>
      <webElementGuid>5de37ec7-e942-4eec-a9bb-20a37b0af04d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
