<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Self-billed Refund Note_ant-input css-4fk4bg_1_2</name>
   <tag></tag>
   <elementGuidId>0c17bd0c-225a-4aea-9854-7213c0c5bd9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/main/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/span/span/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.css-4fk4bg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search by e-invoice No.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6345010f-9ac6-46a8-bc06-24254580410f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by e-invoice No.</value>
      <webElementGuid>f727d456-1b00-4b1f-bae4-63a62a02417f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>443</value>
      <webElementGuid>a3e8c9ca-b0a1-4bd3-9f4e-090ae557d0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-4fk4bg</value>
      <webElementGuid>2a2901eb-52f8-47a8-9f1a-c0139d85004b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c8361d5-3f1d-4fdc-9b11-8bc6f04a4e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SI</value>
      <webElementGuid>654358d0-5207-4e0c-99e1-b2ddd1dba2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-uaxenf ant-design-pro ant-pro-layout screen-lg ant-pro-layout-fix-siderbar ant-pro-layout-mix&quot;]/div[@class=&quot;ant-layout ant-layout-has-sider css-4fk4bg&quot;]/div[@class=&quot;ant-pro-layout-container css-uaxenf&quot;]/main[@class=&quot;ant-layout-content ant-pro-layout-content css-uaxenf ant-pro-layout-has-header ant-pro-layout-content-has-page-container css-4fk4bg&quot;]/div[@class=&quot;ant-pro-page-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content css-uaxenf&quot;]/div[@class=&quot;ant-pro-grid-content-children css-uaxenf&quot;]/div[@class=&quot;css-uaxenf ant-pro-page-container-children-container&quot;]/div[@class=&quot;ant-card ant-card-bordered ant-card-small css-4fk4bg&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;ant-pro-table invoice-list css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar css-uaxenf sqTableToolbar&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-container css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-right css-uaxenf&quot;]/div[@class=&quot;ant-pro-table-list-toolbar-search css-uaxenf&quot;]/span[@class=&quot;ant-input-group-wrapper ant-input-group-wrapper-outlined css-4fk4bg ant-input-search&quot;]/span[@class=&quot;ant-input-wrapper ant-input-group css-4fk4bg&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused css-4fk4bg ant-input-outlined&quot;]/input[@class=&quot;ant-input css-4fk4bg&quot;]</value>
      <webElementGuid>f9e6a3c5-bb1a-444a-b331-6bab491eef7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='SI']</value>
      <webElementGuid>7ce13f3e-eda7-40e7-b6d1-a652e5211c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/main/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/span/span/span/input</value>
      <webElementGuid>c216d133-a51e-46c8-a748-f1b2e8b4d2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>15e508c1-80ff-49f2-ac51-a362004f23d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search by e-invoice No.' and @type = 'text']</value>
      <webElementGuid>464ac9f5-e67d-47b9-a1a7-5994f351fd73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
