<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas__react-pdf__Page__canvas</name>
   <tag></tag>
   <elementGuidId>439abd66-4bb6-4705-9872-56d9a19f5491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas.react-pdf__Page__canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog >> canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>cc69b4d7-703f-4945-b6dc-7017b551468f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-pdf__Page__canvas</value>
      <webElementGuid>27f4fac7-6f7f-4ad8-a290-de15267e5616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>c9674a2a-1652-4fe8-a027-0cbe8b62b460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1500</value>
      <webElementGuid>a60b4786-3a63-47c2-987f-769593774b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2121</value>
      <webElementGuid>dafd187f-c9c8-4452-bc60-f98989bb62a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[@class=&quot;ant-modal-root css-4fk4bg&quot;]/div[@class=&quot;ant-modal-wrap&quot;]/div[@class=&quot;ant-modal css-4fk4bg&quot;]/div[2]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/form[@class=&quot;ant-form ant-form-vertical css-4fk4bg ant-pro-form css-uaxenf&quot;]/div[@class=&quot;react-pdf__Document&quot;]/div[@class=&quot;react-pdf__Page&quot;]/canvas[@class=&quot;react-pdf__Page__canvas&quot;]</value>
      <webElementGuid>381b0ebb-44ea-414f-aed0-98bb07b46186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/canvas</value>
      <webElementGuid>2b6ec614-0d14-4aac-a206-53dfcfa0bdf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
